name: Node.js and RSpec CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-and-frontend-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js v20.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.12.1'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install

      - name: Change directory to frontend folder
        run: cd frontend

      - name: Install frontend dependencies and build
        run: |
          npm install
          npm run build || true

      - name: Change directory back to the root folder
        run: cd ..

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Set up database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          rails db:create
          rails db:migrate
          rails s &

      - name: Change directory to spec folder
        run: cd spec

      - name: Run RSpec tests
        run: rails spec

      - name: Change directory to frontend/test folder
        run: cd ../frontend/test

      - name: Run Playwright tests
        run: node e2e.spec.js
